### ISSUE TITLE
gnuplot-mode; 

### ISSUE THREAD

**Issue by NikoSauer** [bruceravel/gnuplot-mode#29]

**Comment by NikoSauer** [comment]
Attached is elisp code that will Comment/Uncomment a region in gnuplot-mode. It works in Xemacs. Also attached is a diff to show how I modified gnuplot.el.

**Comment by bruceravel** [comment]
@NikoSauer 
Try using gist (gist is like a scratch pad for the internet -- there is a link at the very top of the page) to post port you code and diff files.  Then make a comment in this issue which contains the links to the gists you created.

Thanks!
Bruce

I'm going to go ahead and reopen this.

**Comment by NikoSauer** [comment]
Hope I did it correctly. 

Niko Sauer

**Comment by NikoSauer** [comment]
Sorry, there was a confusion between Backspace and Enter. Corrected as Issue #30
